openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger StudentStore
  license:
    name: MIT
servers:
  - url: '{protocol}:////localhost:8080/v1'
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
paths:
  /students:
    get:
      summary: List all students
      operationId: listStudents
      tags:
        - student
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of students
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Students"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /student/add:
    post:
      summary: Create a Student
      operationId: createStudent
      tags:
        - student
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /student/{studentId}:
    get:
      summary: Info for a specific student
      operationId: showStudentById
      tags:
        - student
      parameters:
        - name: studentId
          in: path
          required: true
          description: The id of the student to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Student"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Student:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Students:
      type: array
      items:
        $ref: "#/components/schemas/Student"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string